image: harbor.mbank.kg/cbk/cbk-builder:0.0.7

stages:
  - test
  - build
  - helm

variables:
  CI_DEBUG_TRACE: "false"
  HELM_REGISTRY: "http://chartmuseum.mbank.kg"
  MAVEN_CLI_OPTS: "--batch-mode --errors --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

.set-version-feature: &set-version-feature
  - |
    PROJECT_NAME=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.artifactId -q -DforceStdout)
    PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=projectVersion -q -DforceStdout)
    BRANCH_NAME=$(echo "$CI_COMMIT_REF_NAME" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '-' | sed 's/--*/-/g; s/^-*//; s/-*$//' | head -c 30)
    TAG="$PROJECT_VERSION-feature-$BRANCH_NAME-${CI_PIPELINE_IID}"
    echo "Git tag is $TAG"

.set-version-dev: &set-version-dev
  - |
    PROJECT_NAME=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.artifactId -q -DforceStdout)
    PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=projectVersion -q -DforceStdout)
    TAG="$PROJECT_VERSION-dev"
    echo "Git tag is $TAG"

.set-version-hotfix: &set-version-hotfix
  - |
    PROJECT_NAME=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.artifactId -q -DforceStdout)
    PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=projectVersion -q -DforceStdout)
    TAG="$PROJECT_VERSION-hotfix"
    echo "Git tag is $TAG"

.set-version-release: &set-version-release
  - |
    PROJECT_NAME=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.artifactId -q -DforceStdout)
    PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=projectVersion -q -DforceStdout)
    TAG="$PROJECT_VERSION"
    echo "Git tag is $TAG"

.credential-git-config: &credential-git-config
  - |
    git config --global user.name "$GITLAB_USER_LOGIN"
    git config --global user.email "$GITLAB_USER_EMAIL"
    git config pull.rebase true
    git remote set-url origin https://${PERSONAL_TOKEN_NAME}:${PERSONAL_TOKEN_KEY}@$CI_SERVER_HOST/$CI_PROJECT_PATH.git

.set-tag: &set-tag
  - |
    echo "Commit by $CI_COMMIT_AUTHOR"
    TAG_EXIST=$(git tag -l --sort=refname $TAG)
    if [ -z "$TAG_EXIST" ]; then
        git tag -a $TAG -m "tag from gitlab-ci"
        git push origin "$TAG"
    else
        echo "Tag $TAG alredy exist in $CI_COMMIT_BRANCH branch, please edit version in root pom.xml"
        exit -1 # fail the job
    fi

.docker-build-push: &docker-build-push
  - |
    echo "------Build Docker Image-----"
    PROJECT_NAME=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate \
      -Dexpression=project.artifactId -q -DforceStdout)
    echo "Building image ${HARBOR_HOST}/${HARBOR_PROJECT}/${PROJECT_NAME}:${TAG}"
    docker build -t ${HARBOR_HOST}/${HARBOR_PROJECT}/${PROJECT_NAME}:${TAG} .
    docker push ${HARBOR_HOST}/${HARBOR_PROJECT}/${PROJECT_NAME}:${TAG}
    echo "Docker image pushed to Harbor successfully."
    
.maven-deploy: &maven-deploy
  - |
    echo "------This is apps version $TAG-----"
    mvn $MAVEN_CLI_OPTS deploy --update-snapshots -DprojectVersion="$TAG" -DskipTests=true -DprojectDocker=${HARBOR_HOST}/${HARBOR_PROJECT} -DdefaultInfrRegistry=${HARBOR_HOST}/${HARBOR_PROJECT}

.helm-push: &helm-push
  - echo "------Upload helm-chart-----"
  - helm plugin install https://github.com/chartmuseum/helm-push || true
  - helm plugin list
  - helm repo add helm_registry ${HELM_REGISTRY}
  - ls -al ${CI_PROJECT_DIR}/web-chart/target
  - latest_chart=$(ls -t ${CI_PROJECT_DIR}/web-chart/target/*.tgz | head -1)
  - helm cm-push $latest_chart helm_registry

.helm-delete: &helm-delete
  - |
    echo "Deleting Helm chart: ${PROJECT_NAME}-${TAG}"
    curl -u "${CHARTMUSEUM_USERNAME}:${CHARTMUSEUM_PASSWORD}" -X DELETE "${HELM_REGISTRY}/api/charts/${PROJECT_NAME}/${TAG}"

.skip-ci:
  rules:
    - if: '$GITLAB_USER_EMAIL == $CI_CD_EMAIL'
      when: never
    - when: always

default:
  cache: &global_cache
    key: $CI_PROJECT_NAME
    policy: pull-push
    paths:
      - .m2/repository
      - ./node_modules/
  tags:
    - cbk-docker

test:
  stage: test
  image: node:20-alpine
  only:
    - merge_requests
  script:
    - npm ci
    - npm run test || echo "No tests found, skipping"

build-feature:
  stage: build
  allow_failure: false
  cache:
    <<: *global_cache
    policy: pull
  rules:
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "dev" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
  before_script:
    - docker login -u ${HARBOR_USERNAME} -p ${HARBOR_PASSWORD} ${HARBOR_HOST}
  script:
    - *set-version-feature
    - *credential-git-config
    - *set-tag
    - *docker-build-push
    - *maven-deploy
    - *helm-push

build-dev:
  stage: build
  allow_failure: false
  cache:
    <<: *global_cache
  only:
    - dev
  before_script:
    - docker login -u ${HARBOR_USERNAME} -p ${HARBOR_PASSWORD} ${HARBOR_HOST}
  script:
    - *set-version-dev
    - *credential-git-config
    - *set-tag 
    - *docker-build-push
    - *maven-deploy
    - *helm-push

build-hotfix:
  stage: build
  allow_failure: false
  cache:
    <<: *global_cache
    policy: pull
  before_script:
    - docker login -u ${HARBOR_USERNAME} -p ${HARBOR_PASSWORD} ${HARBOR_HOST}
  script:
    - *set-version-hotfix
    - *credential-git-config
    - *set-tag
    - *docker-build-push
    - *maven-deploy
    - *helm-push
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^hotfix.*/
      when: manual

build-release:
  stage: build
  cache:
    <<: *global_cache
    policy: pull-push
  only:
    - master
  before_script:
    - docker login -u ${HARBOR_USERNAME} -p ${HARBOR_PASSWORD} ${HARBOR_HOST}
  script:
    - *set-version-release
    - *credential-git-config
    - *set-tag
    - *docker-build-push
    - *maven-deploy
    - *helm-push

delete-helm-dev:
  stage: helm
  allow_failure: false
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
      when: manual
    - if: '$CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_REF_NAME == "dev"'
      when: manual
    - when: never
  script:
    - *set-version-dev
    - *credential-git-config
    - *helm-delete

delete-helm-feature:
  stage: helm
  allow_failure: false
  rules:
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "master" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
      when: never
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "dev" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
    - when: never
  script:
    - *set-version-feature
    - *credential-git-config
    - *helm-delete

delete-helm-hotfix:
  stage: helm
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^hotfix.*/'
      when: manual
    - when: never
  script:
    - *set-version-hotfix
    - *credential-git-config
    - *helm-delete

delete-helm-release:
  stage: helm
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "dev" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"'
      when: manual
    - if: '$CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_REF_NAME == "master"'
      when: manual
    - when: never  
  script:
    - *set-version-release
    - *credential-git-config
    - *helm-delete