image:
  repository: ${projectDocker}/${projectName}
  tag: ${projectVersion}
  pullPolicy: IfNotPresent
  containerPort: 80

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 256Mi

nodeSelector: { }
tolerations: [ ]
affinity: { }

strategy:
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 0%

replicas:
  init: 1

revisionHistoryLimit: 5

service:
  type: ClusterIP
  nodePort: 30112