apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ include "${projectName}.version" . }}
  labels:
{{ include "${projectName}.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.image.containerPort }}
      protocol: TCP
      name: http
{{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-{{ include "${projectName}.version" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
